server:
  port: 8809
spring:
  application:
    name: StreamProducer
#  cloud:
#    stream:
#      binders:
#        greetingChannel:
#          destination: greetings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
