spring:
  application:
    name: service1
server:
  port: 8802
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/

#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest